### ISSUE TITLE
Trouble with running npm install

### ISSUE THREAD

**Issue by zgordon** [Automattic/calypso-prettier#11]
Hi!

When I run this 

```
npm i --save-dev "git+https://github.com/Automattic/calypso-prettier.git#calypso-1.5"
```

I get the following error:

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout cfddbfe3ebf550530aef2f1c6c4ea1d9e738d9c1
npm ERR! fatal: reference is not a tree: cfddbfe3ebf550530aef2f1c6c4ea1d9e738d9c1
npm ERR!
```

Does anyone have a suggestion on how to resolve this?

Thanks!

**Comment by samouri** [comment]
Hey @zgordon!

The README.md is out of date. The current branch is #calypso-1.9.
So the command to install calypso-prettier as a drop-in replacement to prettier should be: 

```
npm i --save-dev "git+https://github.com/Automattic/calypso-prettier.git#calypso-1.9"
```

**Comment by samouri** [comment]
I've updated the documentation in https://github.com/Automattic/calypso-prettier/commit/c56b42511ec98ba6d8f72b6c391e0a626e90f531

**Comment by createandcode** [comment]
@samouri - looks like the current readme refers to calypso-1.5 - is that correct?

**Comment by jsnajdr** [comment]
Hi @createandcode, that's an outdated info in the README, thanks for noticing it! Since Prettier 1.5, we upgraded the fork many times and are now in sync with the latest version, 1.13.5.

The `wp-prettier-master` branch is up to date even with the bleeding-edge, yet unreleased version in upstream repo's `master`.

I updated the README.

**Comment by createandcode** [comment]
@jsnajdr - cool thanks!
